### ISSUE TITLE
DynamoDB ends up in an inconsistent state

### ISSUE THREAD

**Issue by mazenmelouk** [atlassian/localstack#108]
When threads are writing to dynamodb it does not respect versioning.
Thus the data ends up in a inconsistent state.
For example persisting in parallel Records R1 & R2 with same key,
both try to update & it's a race condition.
I believe a ConditionalCheckFailedException should be thrown.
I used the same code against the  [Amazon Embedded dynamoDb](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) & it worked fine.

**Comment by whummer** [comment]
Thanks for reporting. We should consider using Amazon's *DynamoDBLocal* instead of *dynalite*. I'll give it a try in the next couple of days and see if works with all existing integration tests.

**Comment by whummer** [comment]
@mazenmelouk Could you please provide a small (yet self-contained) test case to reproduce the error? Thanks

**Comment by whummer** [comment]
@mazenmelouk This should be fixed in commit 0a4ac49744edf1105387d24538f53445622dae82 which now uses Amazon's DynamoDBLocal instead of dynalite. The Docker image is being built and pushed as the latest version `0.4.3`. I'm closing this ticket for now, but please feel free to re-open if the problem persists. Thanks

**Comment by mazenmelouk** [comment]
@whummer Thanks for your help & well done it's fixed now.
I know it's late but I already have a small [code](https://github.com/mazenmelouk/local-stack-dyanmodb) for testing, in case you still need it.
