### ISSUE TITLE
how to config s3 in luigi

### ISSUE THREAD

**Issue by Chyroc-MD** [atlassian/localstack#31]
luigi code:
```python
import luigi
from luigi.contrib.s3 import S3Target, S3Client


class A(luigi.Task):
    def output(self):
        client = S3Client('aws_access_key_id', 'aws_secret_access_key', host='localhost', port=4572)
        return S3Target('s3://fake/test', client=client)

    def run(self):
        with self.output().open('w') as f:
            f.write('test')
```

luigi log:
```log
2017-03-26 16:03:13,543 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.57ms
2017-03-26 16:03:14,552 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.58ms
2017-03-26 16:03:15,557 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.57ms
2017-03-26 16:03:16,568 tornado.access[58422] INFO: 200 GET /api/ping (::1) 1.37ms
2017-03-26 16:03:17,576 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.66ms
2017-03-26 16:03:18,587 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.79ms
2017-03-26 16:03:19,598 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.69ms
2017-03-26 16:03:20,607 tornado.access[58422] INFO: 200 GET /api/ping (::1) 0.56ms
```

so，i can not access to s3 by the config.（我不能在luigi里面使用这些代码和配置连接到s3）

I know that is a question of luigi configuration，because I can be connected by a command `aws`（我知道这是我配置的问题，因为在命令行里面，使用aws是可以连接到s3的）

So, I want to ask, how in luigi configuration to connect to the s3？？（所以，我想问一下，在luigi里面配置哪些可以连接到fake-s3）

Thank you very much.（非常感谢，祝你天天开心）

因为我通过aws命令是可以连接的

**Comment by nhducit** [comment]
Please note: The main version of this repository is https://bitbucket.org/atlassian/localstack, please raise PRs against that repo.

**Comment by whummer** [comment]
@Chyroc-MD The problem here is that the underlying S3 client library used by luigi is trying to access the S3 API under the endpoint `fake.localhost:4572`. The reason for this is that, unfortunately, the S3 API relies on the fact that the bucket name is part of the domain name.

There is a workaround. If you have write access to the `/etc/hosts` file, add the following line to it:
```
127.0.0.1       fake.localhost
```
Also, you need to set `is_secure=False` to ensure that the client uses HTTP instead of HTTPS (which is the default):
```
        client = S3Client('aws_access_key_id', 'aws_secret_access_key', host='localhost', port=4572, is_secure=False)
```

If you do **not** have access to your `/etc/hosts` file, you can also specify a proxy host and port:
```
        client = S3Client('aws_access_key_id', 'aws_secret_access_key', host='localhost', port=4572, is_secure=False)
```
The problem, however, is that the access via the proxy currently does not fully work. We need to look into this further.

**Comment by Chyroc-MD** [comment]
thanks!it is ok!
