### ISSUE TITLE
Docker image tags

### ISSUE THREAD

**Issue by c00ler** [atlassian/localstack#32]
Hi!

Do you have any plans regarding docker image tags? We are using localstack since there was no official docker image. As soon as it was added we switched to it. But the latest update broke our build. SQS stopped working. It would be nice to have image tags so it is possible to test new version first.

Thank you for this project. It is really helpful.

**Comment by whummer** [comment]
Yes, this is definitely high up in the priority list. Will try to set this up in the next couple of days.

**Comment by c00ler** [comment]
Cool, thank you!

**Comment by whummer** [comment]
Added in d4235e8b7b3a6781ed024f95dd0fa0611bf72a16 . You can now see the latest versions tagged here: https://hub.docker.com/r/atlassianlabs/localstack/tags/ Let me know if you can fix your issue using either version `0.3.2` or `0.3.3`, otherwise we will have to re-construct and push an image for one of the older versions. Thanks

**Comment by c00ler** [comment]
Hi!
The original issue still exists in both images 0.3.2, 0.3.3. I assume that the root cause is the following change:

cmd = '%s/bin/moto_server sqs -p %s **-H %s**' % (LOCALSTACK_VENV_FOLDER, port, **constants.BIND_HOST**)

I will try to find sometime to investigate the issue and will come back to you with the results.
