### ISSUE TITLE
S3 Create Bucket

### ISSUE THREAD

**Issue by lunacity** [atlassian/localstack#43]
Stumped and fishing here...getting an UnknownHostException when I try to create a bucket. I can return a list of empty buckets as shown below, but when I s3.createBucket("hellobucket") it can't resolve the host: "hellobucket.localhost". I've looked through both the localstack project (and the virtual env folder created .pyenv) and can't find any mention where I could manually make a bucket. 

    @org.junit.Test
    public void Test1() {
        String s = "http://localhost:4572/";
        AmazonS3 s3 = new AmazonS3Client(TEST_CREDENTIALS);
        s3.setEndpoint(s);
        System.out.println(s3.listBuckets().toString());

        s3.createBucket("hellobucket");

    }

[]

com.amazonaws.SdkClientException: Unable to execute HTTP request: hellobucket.localhost

**Comment by whummer** [comment]
That is unfortunately the way how the S3 REST API (and hence the Java SDK) works. The design of the S3 API assumes that the bucket name is part of the domain name, hence the S3 Java SDK hardcodes the bucket name into the domain name of the URL used to contact the API.

There is a workaround, though. I was able to run your test by adding the following line to `/etc/hosts`:
```
127.0.0.1       hellobucket.localhost
```

This is only a dirty fix, not really a viable long-term solution (and it might not work on all machines, as it requires root permissions). I guess in order to make this work properly, we'd have to patch the Amazon S3 client library. You could raise a request here: https://github.com/aws/aws-sdk-java

**Comment by whummer** [comment]
@lunacity Can you confirm that the workaround described above works for you, so we can close this ticket?

**Comment by lunacity** [comment]
Sure thing. Thanks for taking the time to reply!

**Comment by JaimeVL** [comment]
There's a better way to get around this issue. If you enable path style access on your client, it will not append the bucket name to your domain name. Here's how you can change it on an `AmazonS3` object:

```
s3.setS3ClientOptions(S3ClientOptions.builder().setPathStyleAccess(true).build());
```

There is also an option to do this if you're using any of the client builder classes:

```
AmazonS3ClientBuilder builder = AmazonS3ClientBuilder.standard();
...
builder.withPathStyleAccessEnabled(true);
AmazonS3 s3 = builder.build()
```

**Comment by c00ler** [comment]
@whummer I think it makes sense to include this information (solution provided by @JaimeVL) to the main readme file. Somewhere in the troubleshooting section. Everyone trying use s3 will experience this problem. What do you think?

**Comment by whummer** [comment]
@c00ler Added to the latest version of the README, thanks.

**Comment by agurtovoy** [comment]
For anyone who is looking for a solution for JavaScript SDK:

```
const s3 = new AWS.S3( { s3ForcePathStyle: true } );
```

**Comment by whummer** [comment]
@jaywon Has this been fixed in the meantime? If not - any chance you can provide a small, self-contained example node.js program to reproduce the issue? Thanks

**Comment by Shardj** [comment]
For the PHP s3 client it's 'bucket_endpoint' I believe, hope this helps someone.

**Comment by a-urth** [comment]
Hey. Is there a way to do same for `go` sdk?

**Comment by hertzsprung** [comment]
> That is unfortunately the way how the S3 REST API (and hence the Java SDK) works. The design of the S3 API assumes that the bucket name is part of the domain name, hence the S3 Java SDK hardcodes the bucket name into the domain name of the URL used to contact the API.
> 
> There is a workaround, though. I was able to run your test by adding the following line to `/etc/hosts`:
> 
> ```
> 127.0.0.1       hellobucket.localhost
> ```
> 
> This is only a dirty fix, not really a viable long-term solution (and it might not work on all machines, as it requires root permissions). I guess in order to make this work properly, we'd have to patch the Amazon S3 client library. You could raise a request here: https://github.com/aws/aws-sdk-java

This workaround would be particularly suitable when running inside Docker or testcontainers.  But, since localstack doesn't understand virtual host style, it ignores the Host request header, parses the bucket name from the URL path instead, and responds with "bucket not found".

Since localstack already knows its `HOSTNAME_EXTERNAL`, would it be straightforward to parse the Host request header and use it as the bucket name?

**Comment by h4l** [comment]
For the AWS Javascript SDK V3 you need to use the [forcePathStyle](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/bucketendpointinputconfig.html#forcepathstyle) option for `S3Client`:
```
const s3Client = new S3Client({
  // localstack doesn't support domain name bucket addressing by default.
  // Without this, we get DNS errors trying to look up
  // <bucket-name>.localstack or <bucket-name>.localhost
  forcePathStyle: true,

  credentials: {
    accessKeyId: 'fake',
    secretAccessKey: 'fake',
  },
  endpoint: awsEndpointUrl,
  region: 'us-east-1',
});
```

**Comment by andrea-mauro** [comment]
Also from `AmazonS3Builder.setPathStyleAccessEnabled` documentation: _The default behaviour is to detect which access style to use based on the configured endpoint (an IP will result in path-style access)..._
So basically if you specify `127.0.0.1` instead of `localhost` you'll end up with `pathStyleAccessEnabled=true`.
I've just tried it and it actually works.
