### ISSUE TITLE
how to connect to s3 from presto

### ISSUE THREAD

**Issue by Chyroc-MD** [atlassian/localstack#59]
in presto:
`create schema fake with (location='s3://fake/org/')`
return error: 
`Query 20170408_181852_00108_w3kra failed: Got exception: java.io.IOException No FileSystem for scheme: s3`

so , how to add `--endpoint-url='http://localhost:4572'`?

**Comment by whummer** [comment]
Thanks for your request. Please provide more details regarding your use case. Some questions:
* When you say "Presto", I'm assuming you mean the SQL Query Engine (https://prestodb.io/)?
* Which version of Presto are you using?
* Are you running Presto on your local machine? What is the exact setup? Does it run in Docker containers, one JVM process, multiple JVM processes, ...?
* Can you provide a stack trace with more error details (i.e., which class is throwing this exception: `No FileSystem for scheme: s3`)?

It seems there might be a problem with your Presto installation. Your `create schema ...` query looks ok to me (similar to the example here: https://prestodb.io/docs/current/connector/hive.html#examples), but the error message indicates that Presto cannot interpret the `s3://` URL, maybe because some required S3 JARs are missing (?). This error has nothing to do with LocalStack, unfortunately there is not much we can do at this point.

Can you fix your environment so that Presto can connect to the public S3 service on AWS (you could simply create an S3 bucket on AWS, or even use any existing public S3 bucket), then we can investigate any further how to connect Presto to LocalStack. Thanks

**Comment by whummer** [comment]
Any update on this issue, @Chyroc-MD? Have you been able to connect Presto to a public S3 bucket on AWS?

**Comment by Chyroc-MD** [comment]
Sorry, it did not take time recently to test with this repo. Maybe you can close the issue, wait until I return to this issue, I will come to open the issue, thank you.

**Comment by ramyarajasekaran** [comment]
Hey! i have the same question. How do I connect my test bucket created on localstack to Presto? Presto (forked prestosql) is running in a container. How should I go about specifying connector properties to connect to localstack?
