### ISSUE TITLE
Failing build - Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by mavidser** [atlassian/localstack#67]
It was failing with `pip install` at the `make install` command.
```bash
    File "/private/tmp/pip-build-6jtlmY/localstack/setup.py", line 61, in run
      do_make_install()
    File "/private/tmp/pip-build-6jtlmY/localstack/setup.py", line 41, in do_make_install
      raise e
  subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2
```

```bash
$ make install

make setup-venv && \
		make install-libs && \
		make compile
(test `which virtualenv` || pip install virtualenv || sudo pip install virtualenv)
(test -e .venv || virtualenv .venv)
(. .venv/bin/activate && pip install --upgrade pip)
Requirement already up-to-date: pip in ./.venv/lib/python3.6/site-packages
(test ! -e requirements.txt || (. .venv/bin/activate && pip install -r requirements.txt))
Collecting airspeed==0.5.5.dev20160812 (from -r requirements.txt (line 1))
  Using cached airspeed-0.5.5.dev20160812.tar.gz
Collecting amazon_kclpy==1.4.1 (from -r requirements.txt (line 2))
  Using cached amazon_kclpy-1.4.1.tar.gz
Collecting awscli==1.11.75 (from -r requirements.txt (line 3))
  Using cached awscli-1.11.75-py2.py3-none-any.whl
Collecting boto3==1.4.0 (from -r requirements.txt (line 4))
  Using cached boto3-1.4.0-py2.py3-none-any.whl
Collecting coverage==4.0.3 (from -r requirements.txt (line 5))
  Using cached coverage-4.0.3.tar.gz
Collecting docopt==0.6.2 (from -r requirements.txt (line 6))
  Using cached docopt-0.6.2.tar.gz
Collecting elasticsearch==5.3.0 (from -r requirements.txt (line 7))
  Using cached elasticsearch-5.3.0-py2.py3-none-any.whl
Collecting flask==0.10.1 (from -r requirements.txt (line 8))
  Using cached Flask-0.10.1.tar.gz
Collecting flask_swagger==0.2.12 (from -r requirements.txt (line 9))
  Using cached flask-swagger-0.2.12.tar.gz
Collecting jsonpath-rw==1.4.0 (from -r requirements.txt (line 10))
  Using cached jsonpath-rw-1.4.0.tar.gz
Collecting moto-ext==0.4.32.1 (from -r requirements.txt (line 11))
  Using cached moto-ext-0.4.32.1.tar.gz
Collecting nose==1.3.7 (from -r requirements.txt (line 12))
  Using cached nose-1.3.7-py3-none-any.whl
Collecting pep8==1.7.0 (from -r requirements.txt (line 13))
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting python-coveralls==2.7.0 (from -r requirements.txt (line 14))
  Using cached python_coveralls-2.7.0-py2.py3-none-any.whl
Collecting requests==2.11.0 (from -r requirements.txt (line 15))
  Using cached requests-2.11.0-py2.py3-none-any.whl
Collecting requests-aws4auth==0.9 (from -r requirements.txt (line 16))
  Using cached requests_aws4auth-0.9-py2.py3-none-any.whl
Collecting restricted_pkg_ext==1.1.3 (from -r requirements.txt (line 17))
  Using cached restricted_pkg_ext-1.1.3.tar.gz
Collecting sh==1.11 (from -r requirements.txt (line 18))
  Using cached sh-1.11.tar.gz
Collecting subprocess32==3.2.7 (from -r requirements.txt (line 19))
  Using cached subprocess32-3.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.x only.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cm/y39fj6251mq4zjt0b_v70czm0000gn/T/pip-build-644m2tsd/subprocess32/
make[1]: *** [setup-venv] Error 1
make: *** [install] Error 2


$ python setup.py egg_info                                                                  
running egg_info
creating localstack.egg-info
writing requirements to localstack.egg-info/requires.txt
writing localstack.egg-info/PKG-INFO
writing top-level names to localstack.egg-info/top_level.txt
writing dependency_links to localstack.egg-info/dependency_links.txt
writing manifest file 'localstack.egg-info/SOURCES.txt'
reading manifest file 'localstack.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'localstack/mock/pom.xml'
warning: no files found matching '*.java' under directory 'localstack/mock/src'
no previously-included directories found matching 'localstack/dashboard/web/node_modules'
writing manifest file 'localstack.egg-info/SOURCES.txt'
```

Machine info:
macOS 10.12.4

```
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
$ python --version
Python 2.7.10

$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)

$ java -version
Picked up _JAVA_OPTIONS:
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

$ javac -version
Picked up _JAVA_OPTIONS:
javac 1.8.0_112

$ mvn --version
Picked up _JAVA_OPTIONS:
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T01:09:06+05:30)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.4", arch: "x86_64", family: "mac"

$ node --version
v6.9.1

$ npm --version
3.10.8
```

**Comment by whummer** [comment]
Thanks for reporting. Judging from where the error originates (https://github.com/benoit-pierre/python2-subprocess32/blob/master/setup.py#L9), the pip installation code must at some point get into a state where some Python code is executed/interpreted by a Python 3.x runtime.

Why exactly this is the case is relatively difficult to say because it very much depends on your environment. But we can try to dig a little deeper. First of all we need to understand how your terminal session points to either version of python:

```
which python
ls -la `which python`
```

It can be useful to search for the location of your installed Python versions. If you have the `locate` command installed, you can try the following (alternatively, you can use `find`):
```
locate bin/python2.
locate bin/python3.
```

(No need to post the entire output from the command above, but maybe it helps you extract the main installation folders for Python 2.x and 3.x). Maybe you can also post the relevant content of your `PATH` environment variable (before posting, make sure to obfuscate any parts that could reveal your username etc):
```
echo $PATH
```

Also, can you double-check if there is any custom `$PATH` handling logic in your `~/.profile`, `~/.bash_profile`, or `~/.bashrc`. For instance, if your `~/.bashrc` adds `python` to the system path, then under certain circumstances a process that calls `python` in a sub-shell might in fact call a python 3.x subprocess. This can happen if the command that runs `python` executes in a different shell than `bash` (for instance `sh`), which means that this shell will miss the (`bash`-specific) customizations and hence could fall back to Python 3 instead. This is of course pure speculation, but it could in fact be a possible scenario.

Generally speaking, if you want to avoid Python 2.x vs 3.x problems altogether, it would be advisable to maintain only one version (Python 2.x) and delete the other version. This is not always possible or desired, though, and generally you should be able to run both versions side by side on a single system. By investigating the output of the commands posted above, we may be able to drill down to the root cause of the problem. Thanks

**Comment by whummer** [comment]
Edit: I just figured out that this issue might have already been fixed in the `subprocess32` library (see this pull request: https://github.com/google/python-subprocess32/pull/13/files), but the code has never been released since then. I will look into using a snapshot version of `subprocess32`, which should fix your issue.

**Comment by mavidser** [comment]
Thanks. Upon rechecking the versions, the problem turned out to be the python3 virtualenv which I'd installed at some point, causing `/usr/local/bin/virtualenv -> /usr/local/opt/python3/bin/pyvenv`.

Replacing that with the correct version fixed the issue.

Closing the issue, as I'm not sure if version checks is a part of the setup.

**Comment by whummer** [comment]
Thanks for following up on this issue. We have added a patch in 5f0304d734abb3d7a7e03ed30787464dabad441a to make sure the installation does not fail in the scenario described above.

**Comment by whummer** [comment]
@popcycle - is your question related to the LocalStack platform? I'm not aware that we are using `flask-mongoengine` as a dependency.
