### ISSUE TITLE
SQS purge queue is not working on docker container

### ISSUE THREAD

**Issue by sparrc** [atlassian/localstack#79]
After creating a queue, I am not able to purge it via the docker container.

Appears there might be something wrong with networking/DNS, if you see the incorrect hostname in the error message in the last step below.

Steps to reproduce:

1. run docker container:
```
$ docker run -it --name aws -p 4567-4580:4567-4580 -p 8080:8080 atlassianlabs/localstack
```
2. Create a queue via awscli and verify with list:
```
$ aws sqs create-queue --queue-name "MyQueue"
{
    "QueueUrl": "https://queue.amazonaws.com/345835502413/MyQueue"
}

$ aws sqs list-queues --endpoint-url http://localhost:4576
{
    "QueueUrls": [
        "http://localhost:4576/123456789012/MyQueue"
    ]
}
```

3. Attempt to purge queue:
```
$ aws sqs purge-queue --queue-url "http://localhost:4576/123456789012/MyQueue"

An error occurred (InvalidAddress) when calling the PurgeQueue operation: The address https://queue.amazonaws.com/ is not valid for this endpoint.
```

**Comment by sparrc** [comment]
Might be related to this issue in moto: https://github.com/spulec/moto/issues/626

**Comment by sparrc** [comment]
sorry this can be disregarded, the examples above were inconsistently using --endpoint-url

**Comment by mdboop** [comment]
This issue is very old but it still comes up as one of the first results when googling "sqs purge queue localstack", so I'm just leaving this comment for anyone who might end up here. For what it's worth, @sparrc, your use of `--endpoint-url` is not inconsistent.

When you run `$ aws sqs purge-queue --queue-url "http://localhost:4576/123456789012/MyQueue"`, the cli is using your config/credentials from `~/.aws`, which are probably set up for your AWS account. That's what's happening for me, at least.

You need to pass `--endpoint-url` when purging the queue and specify the localhost endpoint:

`aws sqs purge-queue --endpoint-url http://localhost:4576 --queue-url "http://localhost:4576/foo/bar-queue"`

That should work.
